version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "examples/**"
      - "cdk/example/**"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    exclude-paths:
      - "examples/**"
