[package]
name = "dropkick"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = { version = "1.0.68", features = ["backtrace"] }
askama = { version = "0.11.1", default-features = false }
aws-config = "0.48.0"
aws-sdk-ebs = "0.18.0"
aws-sdk-ec2 = "0.18.0"
camino = "1.1.2"
cargo_metadata = "0.15.3"
clap = { version = "4.1.4", features = ["derive"] }
coldsnap = "0.4.2"
env_logger = "0.10.0"
fs-err = "2.9.0"
indicatif = "0.17.3"
iso9660 = "0.1.0"
log = "0.4.17"
tempfile = "3.3.0"
tokio = { version = "1.25.0", features = ["macros", "rt-multi-thread"] }
