[package]
name = "dropkick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
clap = { version = "4.0.29", features = ["derive"] }
dirs = "4.0.0"
hex = "0.4.3"
lazy_static = "1.4.0"
pgp = "0.9.0"
reqwest = "0.11.13"
sha2 = "0.10.6"
tempfile = "3.3.0"
tokio = { version = "1.23.0", features = ["rt-multi-thread", "macros"] }
